### PR TITLE
Add magnetometer example

### PR DESCRIPTION
**Pull request by robyoung**
Uses LSM303AGR driver from eldruin mentioned here #27 (comment)

This example works on the micro:bit V1.5 and V2. The micro:bit V1.3 uses a different magnetometer.

Depends on #60 but does not need to

### CODE REVIEW

**Comment by eldruin** [comment]
I just released version 0.2.0 of the lsm303agr driver so you can use the published version instead :)

**Comment by therealprof** [comment]
Hm, this includes all of the WIP Board stuff now, is this intended? Probably should turn this into a draft until #60 has landed.

**Comment by therealprof** [comment]
bors try

**Comment by therealprof** [comment]
Haha, or we could just merge the other one. 😅 Sorry for the noise.

**Review by therealprof — APPROVED** [review]
Very nice!

bors r+

**Pull request merged**
