### PR TITLE
Update RTIC examples to use cortex-m-rtic 1.0

### PR DESCRIPTION
**Pull request by mattheww**
I've tested these with a micro:bit v1 only.

### CODE REVIEW

**Comment by mattheww** [comment]
I fear it's time to face the MSRV question as discussed at
https://github.com/nrf-rs/microbit/pull/80#issuecomment-977001166

**Comment by therealprof** [comment]
I'm fine with bumping the MSRV to 1.56.

**Comment by caemor** [comment]
I tested it on the micro:bit v2 and it works well.

Since the msrv issue was already resolved in #86 this pr might be ready for the merge?

**Comment by mattheww** [comment]
I've rebased it on current main in order to resolve a couple of conflicts in Cargo.toml files.

**Review by therealprof — APPROVED** [review]
LGTM, thanks!

bors r+

**Pull request merged**
