### PR TITLE
Updated non-blocking display documenation and added Changelog entry

### LINKED ISSUE #109: Display methods don't require critical section token
The documentation of some methods from the [non-blocking Display struct](https://docs.rs/microbit-v2/0.13.0/microbit/display/nonblocking/struct.Display.html)  state that they must be called from inside a critical section, however, this is not enforced by requiring a [critical section token as an argument](https://docs.rust-embedded.org/book/concurrency/index.html#abstractions-send-and-sync).

I've noticed this on the following methods:
* [`handle_display_event()`](https://docs.rs/microbit-v2/0.13.0/microbit/display/nonblocking/struct.Display.html#method.handle_display_event)
* [`show()`](https://docs.rs/microbit-v2/0.13.0/microbit/display/nonblocking/struct.Display.html#method.show)
* [`clear()`](https://docs.rs/microbit-v2/0.13.0/microbit/display/nonblocking/struct.Display.html#method.clear)
* [`show_frame()`](https://docs.rs/microbit-v2/0.13.0/microbit/display/nonblocking/struct.Display.html#method.show_frame)

I think the methods should require the critical section token, however, changing the methods' signature would be a breaking change.

An alternative would be to add a "safe" version of each of the previous methods that implements the safe functionality but requires the token (for example `safe_show()`) and mark the current versions as deprecated.

If there's an agreement on a solution, I could work on this and open a PR.

### PR DESCRIPTION
**Pull request by videbar**
Fixes #109

### CODE REVIEW

**Comment by winksaville** [comment]
@videbar as a retired programmer but noob to microbit, I don't feel fully qualified to give a formal review, but this LGTM and can approve this if you'd like.

**Comment by therealprof** [comment]
Hm, need to check why the CI passes are failing. Seems the doc tests are invalid.

**Comment by videbar** [comment]
> Hm, need to check why the CI passes are failing. Seems the doc tests are invalid.

As far as I can tell, the error seems to be in this portion of `blocking.rs`:

```
//! The coordiante system is oriented so the 'bottom' (x,4) row is the edge with the edge
//! connector. That means that
//!
//! ```no_run
//! display.show(
//!    &mut timer,
//!    [
//!        [0, 0, 1, 0, 0],
//!        [0, 1, 1, 1, 0],
//!        [1, 0, 1, 0, 1],
//!        [0, 0, 1, 0, 0],
//!        [0, 0, 1, 0, 0],
//!    ],
//!    1000,
//!);
//! ```
```
I'm not super familiar with doc tests, but to me it seems like the CI is trying to compile the example above but fails because it can't find `display` or `timer`.

**Comment by videbar** [comment]
Upon further inspection, it seems like the faulty doc test was recently introduced in #119. For some reason, it seems like the CI only checked the changelog in that PR and the error wasn't caught. I think it should be enough to add
```
//! # use microbit_common as microbit;
//! # use microbit::{
//! #     Board,
//! #     hal,
//! #     display::blocking::Display,
//! # };
//! let board = Board::take().unwrap();
//! let mut timer = hal::Timer::new(board.TIMER0);
//! let mut display = Display::new(board.display_pins);
```
at the beginning of the example.

**Review by therealprof — APPROVED** [review]
Great, thanks for taking care of this.

**Pull request merged**
