### PR TITLE
Refactor LED display modules

### PR DESCRIPTION
**Pull request by robyoung**
Addresses #52 

This change is pretty bold. I'm not sure if it's the right direction to go.

Rename and refactor the two LED display modules so that their APIs are closer to each other and hopefully more familiar to people coming from the micropython APIs.

*Blocking API*
```rust
let mut display = Display::new(pins);
loop {
  display.show(&mut timer, heart, 1000);
  display.clear();
  timer.delay_ms(250u32);
}
```

*Non-blocking API*
```rust
let mut display = Display::new(timer, pins);
display.initialise();

loop {
  display.show(heart);
  timer2.delay_ms(1000u32);
  display.clear();
  timer2.delay_ms(500u32);
}

// in a timer interrupt
display.handle_display_event();
```

## Rename the modules
Move the two modules under a common `display` as `blocking` and `nonblocking` and rename all led examples to display.

I went with display over led as this is the name used in the micropython API.

I went with `blocking` and `nonblocking` under `display` rather than `blocking` and `nonblocking` at the top level like in `embedded-hal` because the non-blocking approach is quite unique to the display driver whereas in `embedded-hal` it's a standard non-blocking approach across the board.

## Introduce simplified non-blocking API
Introduce a struct providing a simplified non-blocking API that is similar to the blocking API as an easier stepping stone towards the tiny-led-matrix.

The simplified API does come with some performance costs. Most notably the fact that the frame setting is done inside the `show` method and therefore inside the critical section. This caused slightly more flickering in debug but had no visible effect in release mode. Throughout the docs I have pointed to the instructions and example for using tiny-led-matrix directly if performance becomes a concern.

### CODE REVIEW

**Comment by mattheww** [comment]
You could consider merging `Display::initialise()` into `Display::new()`. It gives up the flexibility to delay starting the timer, but it makes the interface harder to misuse.

**Comment by mattheww** [comment]
I think `clear()` can just be

    pub fn clear(&mut self) {
        self.display.set_frame(&MicrobitFrame::const_default());
    }

**Comment by robyoung** [comment]
Nice, thanks @mattheww I've added those changes. More generally, do you think this looks sensible?

**Comment by mattheww** [comment]
I think wrapping the public interface up in a `Display` struct which owns the timer and the pins is the right thing to do.

That's what I ended up doing for rmicrobit:
https://docs.rs/rmicrobit/1.0.1/rmicrobit/display/struct.MicrobitDisplay.html

The main difference I see is that I didn't put a frame inside that struct. I think that was just to reduce the time when the timer interrupt is blocked, as you mention.

The other difference is that I had a `free()` which cleans up the hardware state and gives the pins and timer back. That might be worth having, in case someone wants a program that sometimes turns the display off in order to have access to another timer.

**Comment by mattheww** [comment]
To be honest, I'm not sure it's worth mentioning the possibility of using tiny-led-matrix directly. That crate only really exists to support rust-microbit.

Given that you've provided `show_frame()`, maybe the only cost of using `Display` is ~100 bytes of an additional `Frame` instance that might not be used.

If you said that `Display` is the only interface then there'd be no need for separate `initialise_display()` and `handle_display_event()` functions, and I think everything gets a bit easier for someone reading the code to understand.

**Comment by robyoung** [comment]
Oh man, how have I missed rmicrobit until now? That is great!

Thank you so much for your time looking at this. They are some really helpful comments. :bow:

**Comment by robyoung** [comment]
bors try

**Comment by robyoung** [comment]
bors try

**Review by therealprof — APPROVED** [review]
Thanks a lot!

bors r+

**Pull request merged**
