### PR TITLE
v2: Add RTC1 and RTC2 to Board

### LINKED ISSUE #99: RTC1 and RTC2 missing from Board
Hi, I noticed that the [board struct of the microbit-v2 crate](https://docs.rs/microbit-v2/0.13.0/microbit/board/struct.Board.html#) only has one real time counter field, `RTC0`. I checked the [nRF52833 product specification](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf52833%2Fkeyfeatures_html5.html) and it states that there are three real time counters available `RT0`, `RT1`, and `RT2` (page 356). The other two RTC are implemented [on the PAC](https://docs.rs/microbit-v2/0.13.0/microbit/hal/pac/index.html) ([here](https://docs.rs/microbit-v2/0.13.0/microbit/hal/pac/struct.RTC1.html) and [here](https://docs.rs/microbit-v2/0.13.0/microbit/hal/pac/struct.RTC2.html)).

I was wondering if there's a reason why they are not available from the `Board` struct or if I'm missing something (I'm quite new to rust embedded).

### PR DESCRIPTION
**Pull request by videbar**
Closes #99

### CODE REVIEW

**Review by therealprof — CHANGES_REQUESTED** [review]
Please add a CHANGELOG entry.

**Comment by videbar** [comment]
I just added an entry under the unreleased section of the CHANGELOG. If it belongs elsewhere, please let me know.

**Review by jamesmunns — APPROVED** [review]
Looks great, thanks!

bors r+

**Comment by jamesmunns** [comment]
bors cancel

**Pull request merged**
