### PR TITLE
Add missing rtcs

### PR DESCRIPTION
**Pull request by jamesmunns**
This is a do-over of #100 (and #105), but targeting the main branch instead of staging.

closes https://github.com/nrf-rs/microbit/issues/99

### CODE REVIEW

**Review by jamesmunns — COMMENTED** [review]
Sorry again for all the noise.

bors r+

**Comment by jamesmunns** [comment]
Right. I can't approve my own PR. *sigh*.

**Review by diondokter — APPROVED** [review]

**Pull request merged**
